services:
  swoole:
    build:
      context: .
      dockerfile: swoole/Dockerfile
    container_name: swoole_container
    ports:
      - "9501:9501"
    volumes:
      - ./src:/var/www/html/src
      - ./swoole/composer.json:/var/www/html/composer.json
    working_dir: /var/www/html
